apiVersion: v2
name: zig-ai
description: A Helm chart for Zig AI Distributed Inference Engine
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/anachary/zig-ai-inference-engine
sources:
  - https://github.com/anachary/zig-ai-inference-engine
maintainers:
  - name: Zig AI Team
    email: support@zig-ai.com
keywords:
  - ai
  - inference
  - distributed
  - zig
  - machine-learning
annotations:
  category: AI/ML
dependencies:
  - name: prometheus
    version: "15.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled
